# Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1. HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.

In [26]:
import numpy as np
def my_vander(my_array,n="",inc=False):
    list1=[]
    if n=="":
        count=0
        for i in my_array:
            count=count+1
        n=count
    for i in my_array:
        if inc==True:
            temp=0
            for j in range(n):
                list1.append(i**temp)
                temp=temp+1
        else:
            temp=n-1
            for j in range(n):
                list1.append(i**temp)
                temp=temp-1
    print(np.array(list1).reshape(-123,n))

In [27]:
my_vander([1,2,3,4])

[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]


In [29]:
my_vander([1,2,3,4],4)

[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]


# Problem Statement : 

# Solution : 

In [37]:
def moving_avg(my_list,n,k):
    list1=[]
    for i in range(len(my_list)-k+1):
        temp=0
        my_sum=0
        t1=k
        for j in range(t1):
            temp = my_list[i]
            my_sum = my_sum + temp
            i=i+1
        list1.append(my_sum/t1)
    print(list1)
    print("Total no of Values = ", n-k+1)

In [38]:
moving_avg([10,20,30,40,50,60,70,80,90,100],10,4)

[25.0, 35.0, 45.0, 55.0, 65.0, 75.0, 85.0]
Total no of Values =  7
